# config.yml

backend:
  # See https://www.netlifycms.org/docs/authentication-backends/#github-backend
  name: github
  repo: aphcq-association/site-web
  branch: master
  base_url: https://auth.static.dcycle.com
  auth_endpoint: auth/github/alberto56
media_folder: 'assets/uploads'
collections:
  - name: 'blog posts'
    create: true
    label: 'Blog'
    folder: 'docs/_posts/'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: "members"
    label: "Members"
    editor:
      preview: false
    files:
      - label: "Members"
        name: "members"
        create: true
        file: "_data/members.yml"
        fields:
          - label: "Members"
            name: "items"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: "Github Username", name: github, widget: string}
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Adhérez'
        name: 'adherez'
        file: 'docs/adherez.html'
        fields:
          - { label: 'Titre', name: 'titre', widget: 'texte' }
