email_contact: aphcq.histoire@gmail.com
email_paypal: aphcq.histoire@gmail.com
copyright_holder: Association des professeures et des professeurs d'histoire des collèges du Québec
base: /
sections:
  - id: home
    href: index.html
    titre: Accueil
  - id: apropos
    href: apropos.html
    titre: Qui sommes-nous?
