---
titre: "Association des professeures et des professeurs d’histoire des collèges du Québec"

couleur_gris_text: "#111"

montrer_infos: "non"

email_contact: "aphcq.histoire@gmail.com"

email_paypal: "aphcq.histoire@gmail.com"

copyright_holder: "Association des professeures et des professeurs d'histoire des collèges du Québec"

courte_description: "L’Association des professeures et des professeurs d’histoire des collèges du Québec (APHCQ) est un organisme à but non lucratif regroupant les enseignantes et enseignants en histoire œuvrant dans le réseau collégial."

facebook: "https://www.facebook.com/groups/50431211883/"

bouton_noir:
  texte: "CONGRÈS ANNUEL"
  url: "/2020/03/10/congres-2020.html"

base: /

